---
version: "3.8"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - jackett:/config
      - downloads-ro:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr-dm
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Los_Angeles
    ports:
      - 8191:8191
    restart: unless-stopped
  ombi-dm:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi-dm
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ombi:/config
    ports:
      - 3579
    restart: unless-stopped
  ombi-mu:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi-mu
    environment:
      - TZ=America/Los_Angeles
      - BASE_URL=/ombi
    volumes:
      - ombi-mu:/config
    ports:
      - 3579
    restart: unless-stopped
  radarr-dm:
    image: linuxserver/radarr:nightly
    container_name: radarr-dm
    mem_limit: 6G
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - radarr:/config
      - movies-rw:/movies
      - downloads-rw:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr-dm
    mem_limit: 6G
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - sonarr:/config
      - tv-rw:/tv
      - downloads-rw:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  tautulli:
    image:  ghcr.io/tautulli/tautulli:latest
    container_name: tautulli-dm
    environment:
      - PUID=993
      - PGID=991
      - TZ=America/Los_Angeles
    volumes:
      - tautulli:/config
      - plexlogs:/plex_logs:ro
    ports:
      - "8181:8181"
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=America/Los_Angeles
      - PUID=1027
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /containers/tdarr/server:/app/server
      - /containers/tdarr/configs:/app/configs
      - /containers/tdarr/logs:/app/logs
      - movies-rw:/media
      - /tmp:/temp

networks:
  default:
    external: true
    name: plex_svcs_dm_bridge

volumes:
  downloads-ro:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,ro"
      device: ":/mnt/Seed_Data_Pool/DM/tomac"
  downloads-rw:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Seed_Data_Pool/DM/tomac"
  movies-rw:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/MU_Media_pool/Movies"
  tv-rw:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/DM_Media_Pool/TV"
  plexlogs:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.5,nolock,soft,ro"
      device: ":/containers/plex-dm/db/Library/Application Support/Plex Media Server/Logs"
  ombi:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Jail_Storage/Docker_Persist/ombi-dm"
  ombi-mu:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Jail_Storage/Docker_Persist/ombi-mu"
  radarr:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Jail_Storage/Docker_Persist/radarr-dm"
  sonarr:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Jail_Storage/Docker_Persist/sonarr-dm"
  tautulli:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Jail_Storage/Docker_Persist/tautulli-dm"

