version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    env_file: secrets.env
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8282:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - npm-data/data data:/data
      - npm-data/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    env_file: dbsecrets.env
    restart: unless-stopped
    volumes:
      - npm-db:/var/lib/mysql

volumes:
  npm-data:
  npm-db: