---
version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  varken:
    container_name: varken
    image: boerderij/varken
    volumes:
      - varken-config:/config
    env_file: varken.env
    restart: unless-stopped
    networks:
      - system_monitoring_default
      - plex_svcs_bridge

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://grafana:3000/adm/grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8282:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    command:

      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "2003:2003"
      - "8086:8086"
    restart: unless-stopped

networks:
  system_monitoring_default:
    external: true
  plex_svcs_bridge:
    external: true

volumes:
  influxdb-data:
  prometheus-config:
  prometheus-data:
  grafana-data:
  varken-config:
