---
version: "3.3"
services:
  mysql:
    container_name: semaphore-mysql
    restart: unless-stopped
    networks:
      - system_svcs_bridge
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    env_file: mysql.env
  semaphore:
    container_name: semaphore
    restart: unless-stopped
    networks:
      - system_svcs_bridge
    ports:
      - 3001:3000
    image: semaphoreui/semaphore:latest
    env_file: semaphore.env
    depends_on:
      - mysql # for postgres, change to: postgres 
  swag:
    image: linuxserver/swag
    container_name: swag
    ports:
      - 443:443
      - 80:80
    networks:
      - portainer_default
      - plex_svcs_bridge
      - system_monitoring_bridge
      - torrent_svcs_bridge
    volumes:
      - letsencrypt-data:/config
    restart: always
    environment:
      - EMAIL=
      - URL=derekflix.tv
      - SUBDOMAINS=www,request,
      - TZ=America/Los_Angeles
      - EXTRA_DOMAINS=uppyflix.tv
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    networks:
      - system_svcs_bridge
    environment:
      - CLEANUP=true
      - INTERVAL=21600
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=influxdb postgres mariadb swag
      - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  

networks:
  plex_svcs_bridge:
    external: true
  portainer_default:
    external: true
  system_monitoring_bridge:
    external: true
  torrent_svcs_bridge:
    external: true

volumes:
  letsencrypt-data:
  semaphore-mysql:
