---
version: "3.3"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    ports:
      - 443:443
      - 80:80
    networks:
      - system_svcs_bridge
      - plex_svcs_dm_bridge
      - vBridge
    volumes:
      - letsencrypt:/config
    restart: always
    environment:
      - EMAIL=
      - URL=derekflix.tv
      - SUBDOMAINS=www,request,
      - TZ=America/Los_Angeles
      - EXTRA_DOMAINS=uppyflix.tv
  smtp:
    container_name: smtp_relay
    image: namshi/smtp
    environment:
      - DISABLE_IPV6
      - RELAY_NETWORKS=:10.10.10.0/24
      - RELAY_NETWORKS=:172.16.0.0/24
    ports:
      - "25:25"
    networks:
      - system_svcs_bridge
      - vBridge
      - plex_svcs_dm_bridge
      - rut-svcs-dm_default

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    networks:
      - system_svcs_bridge
    environment:
      - CLEANUP=true
      - INTERVAL=21600
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=influxdb postgres mariadb swag
      - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  

networks:
  system_svcs_bridge:
    external: true
  vBridge:
    external: true
  plex_svcs_dm_bridge:
    external: true
  rut-svcs-dm_default:
    external: true

volumes:
  letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.30,nolock,soft,rw"
      device: ":/mnt/Jail_Storage/Docker_Persist/letsencrypt"

