---
version: "2"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex-mu
    environment:
      - PUID=1041
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /containers/plex-mu/db:/config
      - /containers/plex-mu/transcode:/transcode
      - /mnt/media/MU:/data
    ports:
      - "32401:32400"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

networks:
  default:
    external:
      name: plex_mu_bridge
