---
version: "2"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex-dm
    environment:
      - PUID=994
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /containers/plex-dm/db:/config
      - /tmp:/transcode
      - /mnt/media/DM:/data
    ports:
      - "32400:32400"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
networks:
  default:
    external:
      name: plex_dm_bridge
