---
version: "2"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex-dm
    environment:
      - PUID=994
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - plex-dm-config:/config
      - /tmp:/transcode
      - tv-ro:/data/TV
      - movies-ro:/data/Movies
    ports:
      - "32400:32400"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  plex-mu:
    image: plexinc/pms-docker
    container_name: plex-mu
    environment:
      - PUID=994
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - plex-mu-config:/config
      - /tmp:/transcode
      - tv-ro:/data/TV
      - movies-ro:/data/Movies
    ports:
      - "32401:32400"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    
    
volumes:
  plex-dm-config:
  plex-mu-config:
  movies-ro:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.100,nolock,soft,ro"
      device: ":/mnt/MU_Media_pool/Movies"
  tv-ro:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.30.100,nolock,soft,ro"
      device: ":/mnt/DM_Media_Pool/TV"

networks:
  default:
    external:
      name: plex_server_bridge